### ISSUE TITLE
cif3 plugin -- output queue.Queue() hanging on get()

### ISSUE THREAD

**Issue by mdavis332** [tenzir/threatbus#29]
Hi @0ortmann and team,

ich bin zurueck =/

Trying to finish up an app plugin for threatbus to send out to another threat intel system (CIFv3). Setup is working fine and I can get threatbus started up with the cif3 plugin. The primary objective is to take submissions from MISP and eventually send them on to CIF. 

However, the issue I've run into is that while the zmq sub to MISP seems to be picking up new attributes and sending them out to threatbus/intel topic, the call to queue.Queue().get() at https://github.com/mdavis332/threatbus/blob/master/plugins/apps/threatbus_cif3/plugin.py#L42 is hanging. If I take the `if watched_queue.empty()` bit out and just let it rely on the get() timeout, it cycles back around fine every 15 seconds. However, the second an Intel item is picked up by the queue, the loop never cycles again and never moves forward. 

Any thoughts? Thanks again for your help.

**Comment by 0ortmann** [comment]
Hi @mdavis332,

I tested your code and noted the following things:

- The items received from that queue are of type `Intel`, not sighting. From the function name vs. the comment / code I'd say you may have mixed up things a bit?
- The wrong type assumption leads to an error when trying to read the `.intel` field which does not exist in the `Intel` data type ([Line 51](https://github.com/mdavis332/threatbus/blob/master/plugins/apps/threatbus_cif3/plugin.py#L51) ff.)
- The try-catch only catches `Empty`. Everything else will bubble up and eventually kill the Thread, hence no new items can be received.
- You don't need the `threading.Lock` in the `receive_intel_from_backbone` function, at least not when simply reading from the queue. Both, the [Logger](https://docs.python.org/3/library/logging.html#thread-safety) and [Queue](https://docs.python.org/3/library/queue.html) are threadsafe by design. I'm not familiar with the `cif` python class and maybe a lock is required to use that one.
- There is no need to check if the queue is empty, we can achieve the same with a blocking `.get` - that's one of the reasons why we decided to use Threads over async.

Here is a minimal working example to receive intel:

```
def receive_intel_from_backbone(watched_queue):
    global logger, cif
    logger.debug(f"Entering receive_intel_from_backbone func to monitor queue {watched_queue}...")
    if not cif:
        logger.debug('No global CIF found. Exiting function')
        return
    while True:
        intel = watched_queue.get()
        if not intel:
            logger.warning('Received empty intel message')
            continue
        logger.info(f"Got intel from Threat Bus {intel}")
```

**Comment by mdavis332** [comment]
> Hi @mdavis332,
> 
> I tested your code and noted the following things:
> 
> * The items received from that queue are of type `Intel`, not sighting. From the function name vs. the comment / code I'd say you may have mixed up things a bit?

Definitely going for `Intel` since that seems to be the correct topic to get info published by MISP. There was a lot of copy/paste code from your MISP plugin, hence why some variable names were still confusing. I've corrected that.

> * The wrong type assumption leads to an error when trying to read the `.intel` field which does not exist in the `Intel` data type ([Line 51](https://github.com/mdavis332/threatbus/blob/master/plugins/apps/threatbus_cif3/plugin.py#L51) ff.)

Another remnant of the copy/paste that I hadn't yet corrected. Since I wasn't getting an error at that line, I didn't think it was getting that far. Now I'm not sure that the the error wasn't just being swallowed up somewhere.

> * The try-catch only catches `Empty`. Everything else will bubble up and eventually kill the Thread, hence no new items can be received.

Gotcha.


> * You don't need the `threading.Lock` in the `receive_intel_from_backbone` function, at least not when simply reading from the queue. Both, the [Logger](https://docs.python.org/3/library/logging.html#thread-safety) and [Queue](https://docs.python.org/3/library/queue.html) are threadsafe by design. I'm not familiar with the `cif` python class and maybe a lock is required to use that one.
> * There is no need to check if the queue is empty, we can achieve the same with a blocking `.get` - that's one of the reasons why we decided to use Threads over async.

I had actually just made the change to watch for empty, lock, and bubble up Empty exceptions right before submitting this GH issue. It was a last ditch effort to try to get things working when they hadn't been without those things.

> 
> Here is a minimal working example to receive intel:
> 
> ```
> def receive_intel_from_backbone(watched_queue):
>     global logger, cif
>     logger.debug(f"Entering receive_intel_from_backbone func to monitor queue {watched_queue}...")
>     if not cif:
>         logger.debug('No global CIF found. Exiting function')
>         return
>     while True:
>         intel = watched_queue.get()
>         if not intel:
>             logger.warning('Received empty intel message')
>             continue
>         logger.info(f"Got intel from Threat Bus {intel}")
> ```

Thank you again for the suggestions. I'm starting to suspect the thread locks were somehow related to the problem I was having. Once I commented those out, things started behaving more normally. 

It does appear to be functional at this point. There are some things that will have to be thought through for use. For example, CIF wants unique tags and confidence per indicator submitted but there appears to be no good way to get this info from MISP from just the attributes. Right now, tags and confidence are being set globally in the config.yaml and would apply to any indicators from MISP to CIF (not ideal). 

At any rate, [https://github.com/mdavis332/threatbus/tree/master/plugins/apps/threatbus_cif3](https://github.com/mdavis332/threatbus/tree/master/plugins/apps/threatbus_cif3) now appears to be working. I can create a PR for this plugin if there's interest, though obviously python queues/threading are not my cup of tea and there are a lot of debug statements scattered about I used for .... well, debugging :)

Thanks again @0ortmann !

**Comment by 0ortmann** [comment]
Sure, we'd welcome that PR! :+1: Do I understand correctly that this issue is resolved? :)

Before submitting your PR please make sure to check our [contributing guidelines](https://github.com/tenzir/.github/blob/master/contributing.md) and please run `make format` on the code. Also please check the README.md such that it does not duplicate the MISP readme and put some info in there what this plugin offers to the user and how it can be configured.

**Comment by mdavis332** [comment]
Yep, issue resolved, closing. I'll check out the guidelines and review the README again to ensure I've covered what's requested before submitting a PR.
