### ISSUE TITLE
Zeek Broker error (Broker::PEER_UNAVAILABLE): (invalid-node, *localhost:47760, "unable to connect to remote peer

### ISSUE THREAD

**Issue by nillay** [tenzir/threatbus#89]
Hello sir,
While solving the issue #82 I have encountered new issue. I have tried installing into fresh system. And reinstalled all the components again freshly. So here are the following conclusion I have reached till this point:
1- when I am compiling the threat bus and other tools like inmem, misp, zeek from the cloning the github, its not installing properly for some reasons. threatbus was stucking at :
`2020-12-16 17:57:31 INFO     [threatbus] Starting plugins...`

2- What is working for me in that in "venv" envoirnment running the following command for installing threatbus and related utilities using:
```
pip install threatbus
pip install threatbus-inmem
pip install threatbus-misp
pip install threatbus-zeek
```

3- Seems like since the day zeek has been updated there is some issue started occurring between zeek and threatbus communication, because zeek version i am running is: 3.2.3

4- Threatbus misp communication is working fine for me.
So now the persistent issue is as shown in screenshot: (I will replace the API key later so didnt hide it here, once all fixed, atleast I hope so)
//Also tried with http://localhost
`error in /opt/zeek/share/zeek/base/frameworks/broker/./log.zeek, line 80: Broker error (Broker::PEER_UNAVAILABLE): (invalid-node, *localhost:47760, "unable to connect to remote peer")`

 
![Screenshot from 2020-12-16 17-58-01](https://user-images.githubusercontent.com/2316795/102349450-5b706100-3fc9-11eb-9c19-986878d68d45.png)

Sir, if my issue can be resolved, I will be very grateful to you.Thank you very much. 

Kind Regards
Nillay

**Comment by 0ortmann** [comment]
Hi @nillay 

1. > when I am compiling the threat bus and other tools like inmem, misp, zeek from the cloning the github, its not installing properly for some reasons. threatbus was stucking at : `020-12-16 17:57:31 INFO [threatbus] Starting plugins...`

That is the case when no plugins are installed. You can install Threat Bus and plugins directly from source as follows:

- clone the [tenzir/threatbus](https://github.com/tenzir/threatbus/) repository via `git clone git@github.com:tenzir/threatbus.git`
- navigate to the repository root folder `cd threatbus`
- install the Threat Bus *and the plugins you need* directly from source: 
```
pip3 install . 
pip3 install plugins/apps/threatbus_misp
pip3 install plugins/apps&& && /threatbus_zeek
pip3 install plugins/backbones/threatbus_inmem
```

Note that it is not enough to just install Threat Bus, as it does not do anything without plugins.

2. > What is working for me in that in "venv" envoirnment running the following command for installing threatbus and related utilities [...]

 That is because you install Threat Bus *and the plugins* from PyPI. You can achieve the same by installing from source as described above.

3. > Seems like since the day zeek has been updated there is some issue started occurring between zeek and threatbus communication, because zeek version i am running is: 3.2.3

I started both Threat Bus and Zeek locally, using Zeek version v3.2.3. I cannot reproduce any errors, the communication works fine on my test machine.

4. > So now the persistent issue is as shown in screenshot

The original Zeek script we provide in [threatbus/apps/zeek](https://github.com/tenzir/threatbus/tree/master/apps/zeek) uses port 47761. From your screenshot I can tell that you modified the Zeek script and changed the port to 47760. To make sure you did not accidentally change anything else, please revert the Zeek script to the original state as we provide it in the repository. To start Zeek with a different Threat Bus port, don't change the script, but instead pass the port as command line option as follows:
```
zeek -i enp0s3 -C threatbus.zeek -- "Tenzir::broker_port=47760/tcp"
```

Does the error persist?

In case the error persists:

- please run `netstat -tulpen` and paste the output
- please clone the Threat Bus repository and run [this Zeek test script](https://github.com/tenzir/threatbus/blob/master/tests/utils/zeek_sender.py) via `python3 zeek_sender.py`: The script will send a message to Threat Bus on `localhost:47761`  via `broker`. This should lead to a Debug log message in Threat Bus.

**Comment by nillay** [comment]
@0ortmann sir,
Thank you for detailed steps to reproduce the issue, I have tried all the steps mentioned above, and attaching the screenshot of the current updates, Also when I am running the zeek_sender.py using python3, threatbus is responding properly but for some reasons zeek in not doing the same. May be something I doing seems to be very foolish, since It was working before. Also want to drag your attention to the fact that when I tried installing from the threatbus folder, after all installation is done, threatbus is not able to connect to broker and throwing error about no broker module found. But anyway once all done and threatbus started finding the broker component, I am hereby attaching the screenshot for the same. Thanks a lot sir for taking our precious time for helping me troubleshooting the issue. I thank you from bottom of my heart.

![Screenshot from 2020-12-16 23-13-26](https://user-images.githubusercontent.com/2316795/102386643-51fcee00-3ff5-11eb-9720-52c4937912aa.png)
![Screenshot from 2020-12-16 23-09-47](https://user-images.githubusercontent.com/2316795/102386648-532e1b00-3ff5-11eb-9dc0-e5a89e825f3a.png)
![Screenshot from 2020-12-16 23-09-42](https://user-images.githubusercontent.com/2316795/102386652-53c6b180-3ff5-11eb-93b5-34acb21769ad.png)

**Comment by 0ortmann** [comment]
1. `Zeek/Broker` can unfortunately not be installed via `pip` / is not available on PyPI. Instead, one has to install it manually. When working in a virtualenv, you need to make your system's site-packages available to the virtualenv, otherwise it cannot find broker. I.e. create it with  `--system-site-packages`, like this:
```
python3 -m venv --system-site-packages venv
```
2. Please note that we released a new version of Threat Bus yesterday. Please update to the latest version, if possible.
3. Thanks for the output of `netstat`. I'm at a loss understanding why Zeek won't find the connection to Threat Bus. What versions are you using exactly for 
- Zeek `zeek --version`
- Broker `python3 -c "import broker; print(f'{broker.Version.MAJOR}.{broker.Version.MINOR}.{broker.Version.PATCH}')"
1.4.0`
- Ubuntu `uname -a`
Lastly, how did you install Zeek and Broker - did you build from source or do you use `apt` packages, and if so, from where did you download it?

**Comment by nillay** [comment]
@0ortmann sir, thanks a lot for taking your precious time in understanding the issue.... and thank you very much for detailed pointers on the queries I am having. Sir I have updated the the threatbus just now by pulling the fresh copy from git here, so now I am sharing the current situation as follows:

> python3 -m venv --system-site-packages venv
Sir I just updated my venv using above command into my environment. Then compiled the broker, threatbus after that by the latest gits. 

Sir for me also Its kinda nightmware that why zeek is not talking to threatbus, when it was doing perfectly once. for some reason Zeek is not able to find the running threatbus pub/sub agent. I installed the zeek and all tools freshly on another machine to check if issue persist. And surprisingly it is occurring even in fresh machine.

----------
One question I want to ask:
I found that you also prepared zeek+broker docker, also the threatbus. I was trying to use that but I am unable to understand how can I supply threatbus.zeek file to zeek since "-v" is reserved for version info in zeek..... I want to try that too, I hope that it may work, but not confident enough that how to supply custom zeek scripts like threatbus.zeek and how to tweak the local.zeek. Although git of that docker explains a lot of commands, I tried them but may be I am failing to understand the usage properly.

Anyways here are following information I am trying to provide related to the issue:

_**Zeek Version:**_
![Screenshot from 2020-12-17 17-02-30](https://user-images.githubusercontent.com/2316795/102485194-46f59c80-408d-11eb-8738-24e3bd885b36.png)

_**Firewall status:**_
![Screenshot from 2020-12-17 17-13-51](https://user-images.githubusercontent.com/2316795/102485192-465d0600-408d-11eb-88c4-31488494ca46.png)

_**Cheking Threatbus + Zeek communication again:**_
![Screenshot from 2020-12-17 17-14-50](https://user-images.githubusercontent.com/2316795/102485188-45c46f80-408d-11eb-9ec3-6c0e2eecee2f.png)

_**python3 -c "import broker; print(f'{broker.Version.MAJOR}.{broker.Version.MINOR}.{broker.Version.PATCH}')"**_
![Screenshot from 2020-12-17 17-15-13](https://user-images.githubusercontent.com/2316795/102485183-452bd900-408d-11eb-94a3-e65c9babb1d7.png)

_**uname -a**_
![Screenshot from 2020-12-17 17-15-43](https://user-images.githubusercontent.com/2316795/102485181-43faac00-408d-11eb-80f0-2460d0abf150.png)

_**System update status for update and dist-upgrade:**_
![Screenshot from 2020-12-17 17-16-06](https://user-images.githubusercontent.com/2316795/102485176-42c97f00-408d-11eb-83d2-2bb21dfd101e.png)

----------
**How did I Install Zeek:**
_Dependencies:_
```
$ sudo su
$ apt-get update
$ apt-get upgrade
$ apt install curl
$ apt-get install cmake make gcc g++ flex bison libpcap-dev libssl-dev python-dev swig zlib1g-dev
$ echo 'deb https://download.opensuse.org/repositories/security:/zeek/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/security:zeek.list
$ curl -fsSL https://download.opensuse.org/repositories/security:/zeek/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/security:zeek.gpg > /dev/null
$ sudo apt-get update
```
_Zeek:_
`$ sudo apt-get install zeek`

_Verifying if Zeek installed correctly:_
```
$ /opt/zeek/bin/zeek –h
```
 As root/sudo, create the /opt/zeek directory and set ownership to the zeek user.
sudo chown -R user:user /opt/zeek <my user name in place of "user">
sudo chmod 750 /opt/zeek

**How did I Install Broker:**

I tried both python2 virtualenv and python3 venv for creating the venv envoirnment:

Installing venv (Python3):
```
$ cd /Users/user/sandbox/broker/
$ python3 -m venv ./venv
```
Activated venv:
`. /Users/user/sandbox/broker/venv/bin/activate`

Brief:
As per zeek broker documentation,zeek uses C++ actor frameworks. although zeek broker git provides caf bundled with the package. I tried two ways, first was the Installation of CAF separately and then installation of Zeek Broker with python dependencies. Second way the using of CAF comes with Zeek broker itself.

**How did I Install CAF as first alternative way as Broker dependency:**

```
$ git clone --recursive https://github.com/actor-framework/actor-framework
$ cd actor-framework
$ ./configure
$ cd build
$ make
$ make test
$ sudo make install
```
**Installation of Zeek Broker with Python Dependencies:** (While keep activating the "venv")
```
$ git clone --recursive https://github.com/zeek/broker
$ ./configure --prefix=/Users/user/sandbox/broker --python-prefix=$(python -c 'import sys; print(sys.exec_prefix)')
$ make install
$ python -c 'import broker; print(broker.__file__)' /Users/user/sandbox/broker/venv/lib/python3.7/site-packages/broker/__init__.py
```
(last command reflects the path if broker installed properly otherwise gives error.)

**How did I Installed Threatbus**
Although this command gives error:
```
pip3 install plugins/apps&& && /threatbus_zeek
bash: syntax error near unexpected token `&&'
```
**_But here is the way threatbus and additional plugins was installed:_**
```
$ git clone --recursive https://github.com/tenzir/threatbus
$ cd threatbus
$ pip3 install .
$ pip3 install threatbus
$ pip3 install plugins/apps/* 
$ pip3 install plugins/apps/threatbus_misp
$ pip3 install plugins/backbones/threatbus_inmem
```
Sir, so i tried here to provide all the process I followed to install the abovesaid tools. Please let me know if any other details are required too.

Kind Regards
Nillay

**Comment by 0ortmann** [comment]
Hi @nillay 
You are using Broker `2.1.0` and Zeek `3.2.3`. These versions are *not compatible*. See the [Broker 2.0.0-rc1 release notes](https://github.com/zeek/broker/releases/tag/v2.0.0-rc1):
> Broker 2.0.0 now depends on CAF 0.18.0 with a wire format targeting compatibility with Zeek 4.0.x.

Please use Broker `1.4.0`.

When you build Broker, simply check out the Broker release version via 
```
cd broker
git checkout v1.4.0
git submodule update --init --recursive
```
Then install Broker like usual.

**Comment by nillay** [comment]
Sigh! Sir what a relief! I was completely clueless about the cause. Sir, Can't thank you enough for saving me. I am and will always be grateful for the kind of pain you took to help me out. 

Attaching screenshot for the same:
![Screenshot from 2020-12-17 22-27-23](https://user-images.githubusercontent.com/2316795/102522215-fb0e1c00-40bb-11eb-8fb7-559363e42811.png)
![Screenshot from 2020-12-17 22-53-50](https://user-images.githubusercontent.com/2316795/102522210-f9445880-40bb-11eb-97c0-4b12709c5c75.png)
![Screenshot from 2020-12-17 22-55-43](https://user-images.githubusercontent.com/2316795/102522203-f8132b80-40bb-11eb-9716-e1fd8e0c7f4c.png)



Sir, although MISP is not reflecting the incident when its been seen by threatbus and zeek. But atleast now zeek is getting intel from MISP.

Sir, thank you again for all the efforts and precious time you put in helping me out.

Kind Regards
Nillay

> Hi @nillay
> You are using Broker `2.1.0` and Zeek `3.2.3`. These versions are _not compatible_. See the [Broker 2.0.0-rc1 release notes](https://github.com/zeek/broker/releases/tag/v2.0.0-rc1):
> 
> > Broker 2.0.0 now depends on CAF 0.18.0 with a wire format targeting compatibility with Zeek 4.0.x.
> 
> Please use Broker `1.4.0`.
> 
> When you build Broker, simply check out the Broker release version via
> 
> ```
> cd broker
> git checkout v1.4.0
> git submodule update --init --recursive
> 
> 
> Then install Broker like usual.

**Comment by 0ortmann** [comment]
I'm glad we could resolve this issue :)

**Comment by nillay** [comment]
@0ortmann sir all credits goes to you.
